# Copyright 2022 Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################


[project]
name        = "uvml_sb"
full-name   = "Moore.io Scoreboarding Library"
description = ""

[simulation]
preferred-simulators = [ "vivado" ]